[package]
name = "database"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "database"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true
sea-orm-migration.workspace = true
sea-orm.workspace = true
