//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "host")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub machine_id: String,
    pub machine_ip: String,
    pub machine_country: String,
    pub machine_geo: String,
    pub os_family: String,
    pub os_name: String,
    pub os_version: String,
    pub os_arch: String,
    pub os_build: String,
    pub os_virtualization: bool,
    pub hashed_cpu: i32,
    pub hashed_gpu: i32,
    pub hashed_memory: i32,
    pub hashed_disk: i32,
    pub hashed_network: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
